### ISSUE TITLE
Is gexf 1.2 really deprecated?

### ISSUE THREAD

**Issue by greebie** [gephi/gexf#11]
When using Gephi, I receive warnings that 1.2draft is deprecated. However, it also appears that 1.3 is a "work in progress."

Could you please advise on the appropriate way to produce a gexf for importing into Gephi?  Thanks.

**Comment by dwcaraway** [comment]
`1.2` should not be deprecated until `1.3` is in widespread use. The GEXF support libraries in the community are still using `1.1` and `1.2` and will likely not change until the `1.3` spec is published.

**Comment by greebie** [comment]
I agree with @dwcaraway. Deprecation implies that I should upgrade to something newer. When there is nothing to upgrade to, things get confusing and can result in problems.

**Comment by kortschak** [comment]
I've just spent a day covered in XML to put together a parses for GEXF for Go and as part of my testing I've written out GEXF from the examples using Gephi. This breaks the parser because it writes 1.3 (which is mentioned nowhere on gefx.net) and Go's XML handling requires namespace matching. It would be nice to have communication on things like this readily available from the canonical source (presumably gexf.net).

**Comment by mbastian** [comment]
Closing this issues as it has been resolved. All GEXF 1.3 specifications are now official and accessible online. 

We recommend all users and tools to adapt to the 1.3 schema. See details in the [release notes](https://github.com/gephi/gexf/releases/tag/1.3).
